### ISSUE TITLE
escaping not working properly

### ISSUE THREAD

**Issue by jtoy** [michelson/BigBroda#15] opened 2014-11-26 08:43 UTC
this does not work:

string = "{\"ip\"=>\"61.50.163.82\","

BqModel.create :string => string

**Comment by michelson** [comment] 2015-02-13 11:06
@jtoy , sorry for the delay on reply, can't reproduce this issue, 

```
LogData.create(name: "hello")
   (0.0ms)  begin transaction
   (0.0ms)  commit transaction
 => #<LogData id: "abdf5f6ae9da24276f6dcdf27040a9cb", name: "hello", description: nil, created_at: "2015-02-13 11:02:58", updated_at: "2015-02-13 11:02:58">
```

I will close this , please reopen if you still can't get this to work

**Closed by michelson** 2015-02-13 11:06 UTC
